# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.

echo "##### START .zshrc #####"

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Created by newuser for 5.9
source ~/.config/shell/aliases
source ~/.config/shell/variables
source ~/.config/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Add custom source if needed
[[ -f ~/.custom.sh ]] && source ~/.custom.sh

# Extend PATH
typeset -U path PATH
path=(~/.local/bin ~/.local/bin/scripts ~/.local/bin/sway $path)
export PATH

# launch sway
#if [ -z $SSH_TTY ] ; then
#   exec sway
#fi
#
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

echo "#####  END  .zshrc #####"
