---

- name: "[arch_install/configure] Configure Desktop Environment"
  hosts: localhost
  connection: local
  vars_files:
  - ../vars/main.yml
  tasks:
  #- name: "[arch_install/configure] : test sub-elements"
  #  debug:
  #    msg: '"{{ item.0.software}}" : "{{ item.1.src }}"  -> "{{ item.1.dest }}"'
  #  loop: "{{ configuration_files | subelements('files') }}"
  - name: "[arch_install/configure] : deploy configuration files"
    ansible.builtin.file:
      src: "{{ item.1.src }}"
      dest: "{{ item.1.dest }}"
      force: true
      state: link
    loop: "{{ configuration_files | subelements('files') }}"

  - name: "[arch_install/configure] : remove default application entries"
    ansible.builtin.file:
      path: "{{ application_dir }}"
      state: absent
    loop:
    - /usr/share/applications/
    - /usr/local/share/applications/
    loop_control:
      loop_var: application_dir