- name: "[arch_install/install] : enable user services"
  ansible.builtin.systemd_service:
    name: "{{ user_service }}"
    scope: "user"
    enabled: true
  loop: "{{ user_services }}"
  loop_control:
    loop_var: user_service