---

- name: "[arch_install/prerequisites] Install Desktop Environment prerequisites"
  hosts: localhost
  connection: local
  vars_files:
  - ../vars/main.yml
  tasks:
  - name: "[arch_install/prerequisites] : create all directories"
    ansible.builtin.file:
      path: "{{ prerequisites_dir }}"
      state: directory
    loop: "{{ prerequisites_dirs }}"
    loop_control:
      loop_var: prerequisites_dir
  - name: "[arch_install/prerequisites] : add powerlevel10k binaries"
    ansible.builtin.command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /home/nicolas/.config/powerlevel10k
